### ISSUE TITLE
全角→半角処理について

### ISSUE THREAD

**Issue by YUUKIToriyama** [geolonia/normalize-japanese-addresses#109]
Rust移植をつくってみようなどと思いコードを拝読させて頂いております。
src/main.tsを読んでいたとき、次の部分についてふと疑問に思いました。
https://github.com/geolonia/normalize-japanese-addresses/blob/f332bf85b9ca6ff8f6e9e409cb4cedfacc58b5fa/src/main.ts#L60-L63

`zen2han`が
https://github.com/geolonia/normalize-japanese-addresses/blob/f332bf85b9ca6ff8f6e9e409cb4cedfacc58b5fa/src/lib/zen2han.ts#L1-L5  
と定義されているので、二重に正規表現の検索をかけるようになってやや冗長ではないかと思いました。  
まあ、変えたところで速度が格段に上がる箇所ではありませんし、見た目も今のコードのほうが良いのでこだわる必要もありませんが、57行目から63行目は次のようにしても動くようです。

```typescript
let addr = zen2han(address)
  .replace(/　/g, ' ')
  .replace(/ +/g, ' ')
```

**Comment by miya0001** [comment]
@YUUKIToriyama ありがとうございます！

**Comment by miya0001** [comment]
@champierre こちら #110 と一緒に対処して次のリリースに含めていただけますと。

cc: @keichan34
