### ISSUE TITLE
レスポンスに緯度経度を追加する

### ISSUE THREAD

**Issue by miya0001** [geolonia/normalize-japanese-addresses#110]
レスポンスに住所データv2の緯度経度を追加する。

Related: https://github.com/geolonia/community-geocoder/issues/116

**Comment by miya0001** [comment]
@keichan34 @champierre @ShinichiNishikawa 

不動産共通ID の API がトラブらないようにリリースのタイミングを調整していただけますと。

**Comment by keichan34** [comment]
@miya0001 不動産IDはAPI固定しているのでこちらのリリースには問題ないかと。念のためリリース前声かけいただけると助かります

**Comment by champierre** [comment]
@miya0001 リリース済みです。
