### ISSUE TITLE
正規化結果に含まれる「大字」の取り扱い方を正しく理解したい

### ISSUE THREAD

**Issue by hirokoma** [geolonia/normalize-japanese-addresses#114]
お世話になっております。

最近のアップデートにおいて、正規化済みの住所に「大字」の文字列が付加されるようになったと存じております。

① 過去のバージョンでは、正規化済み住所に「大字」が付いていたものと、付いていなかったものが混在していた認識なのですが、最近のアップデートによって「大字」をつけるように統一されたのだと推察されます。「大字」の文字列を付ける方向性で統一するに至った経緯についてお伺いしたいです。

② また、現行バージョンにおいても、過去のバージョンと同じように「大字」が付かない正規化済み住所を得たい場合、 `town` の先頭から `大字` を除去する後処理を入れることで実現しようと考えているのですが、これは十分でしょうか（例外があるかを伺いたいです）。

③ 上記の①と②を踏まえたご質問になるのですが、①で「大字を付与すべき」という判断に至った重要な思想があるのであれば、②で大字を除去する後処理を入れること自体がその思想に反しており、開発者としては推奨されませんでしょうか。

**Comment by miya0001** [comment]
> 「大字」の文字列を付ける方向性で統一するに至った経緯についてお伺いしたいです。

ご指摘の通り、当初は「大字」は削除しておりましたが、現在では、大字の有無については、ベースになっている国土数値情報のデータに追随するように修正しております。
国土数値情報に合わせるようにした理由は、「大字」を削除するべきかどうかは明確には正解がないので、シンプルに国が公開しているデータにリスペクトしたほうが無難だと判断したからです。

> ② また、現行バージョンにおいても、過去のバージョンと同じように「大字」が付かない正規化済み住所を得たい場合、 town の先頭から 大字 を除去する後処理を入れることで実現しようと考えているのですが、これは十分でしょうか（例外があるかを伺いたいです）。

本モジュールをどのように利用されるかについては、こちらではお答えしかねます。自己責任で工夫なさるといいかなと思われます。
