### ISSUE TITLE
「字」の表記有無について

### ISSUE THREAD

**Issue by sekky1983** [geolonia/normalize-japanese-addresses#118]
以下の住所について，「仙台市泉区市名坂字野蔵xxx-yy」と結果が出ることを期待したのですが，
正規化を図っても「字」が表示されません。

入力した住所：仙台市泉区市名坂野蔵xxx-yy
結果：
　{
  "pref": "宮城県",
  "city": "仙台市泉区",
  "town": "市名坂",
  "addr": "野蔵xxx-yy",
  "lat": 38.321917,
  "lng": 140.889669,
  "level": 3
}

※ほかの住所（例：山形県西置賜郡白鷹町鮎貝→pref：山形県，city：西置賜郡白鷹町，town：大字鮎貝）だと，
　（大）字が出ました。

「（大）字」の出る/出ないの規則があるのでしょうか。

**Comment by miya0001** [comment]
このライブラリの元となるデータは国土数値情報に依存しており、「大字」や「字」が出るかどうかについては、国土数値情報にそれらが含まれているかどうかによって変わります。
実際にどのような規則で、それらが含まれたり含まれなかったりするのかは不明ですが、このライブラリでは、国土数値情報に追従することとしております。

質問なので、閉じさせていただきます。
