### ISSUE TITLE
分割がおかしそうな住所について

### ISSUE THREAD

**Issue by jumpei-nishioka** [geolonia/normalize-japanese-addresses#125]
お世話になっております。

住所の正規化時に誤っていそうな正規化を見つけたので報告します。
「本来townに分割される街名や丁目がaddrに分割されてしまっている。」
一番左側が分割前の住所で、その後スペース区切りでpref city town addrで記載しています。
よろしくおねがいします。

```
埼玉県越谷市蒲生茜町9-3 埼玉県 越谷市 大字蒲生 茜町9-3
埼玉県川越市富士見町9-2 埼玉県 川越市 大字富士見 町9-2
埼玉県さいたま市見沼区丸ヶ崎町9-1 埼玉県 さいたま市見沼区 大字丸ヶ崎 町9-1
埼玉県飯能市南町8-35 埼玉県 飯能市 大字南 町8-35
埼玉県越谷市登戸町8-34 埼玉県 越谷市 大字登戸 町8-34
埼玉県川口市芝東町9-12 埼玉県 川口市 大字芝 東町9-12
埼玉県越谷市蒲生東町4-48 埼玉県 越谷市 大字蒲生 東町4-48
埼玉県越谷市蒲生旭町8-31 埼玉県 越谷市 大字蒲生 旭町8-31
埼玉県川口市大字芝字宮根3938-5	埼玉県 川口市 大字芝 字宮根3938-5
神奈川県厚木市三田2丁目3-6	神奈川県 厚木市 三田 二丁目3-6
埼玉県深谷市岡1丁目11-10 埼玉県 深谷市 岡 一丁目11-10
```

**Comment by miya0001** [comment]
@jumpei-nishioka ありがとうございます！

**Comment by miya0001** [comment]
@champierre 

API を見たらデータがありますね。これ `蒲生茜町` の前に `大字蒲生` がマッチしてるっぽいですね。。。

https://geolonia.github.io/japanese-addresses/api/ja/%E5%9F%BC%E7%8E%89%E7%9C%8C/%E8%B6%8A%E8%B0%B7%E5%B8%82.json

![](https://www.evernote.com/l/ABVPCj5XgGFFO4xNONob3-yfuhQRSQpo8u0B/image.png)

**Comment by keichan34** [comment]
@jumpei-nishioka 連絡が遅れて申し訳ありません。

大字と大字なしの似た住所が存在するときのの誤判定を修正するバージョン v2.3.5 を先程リリースしました。

ただし、最初の報告に下記の住所

* 神奈川県厚木市三田2丁目3-6
* 埼玉県深谷市岡1丁目11-10

のデータが不足していたので後ほど追加する予定です。こちらが追加次第改めて連絡いたします。

**Comment by jumpei-nishioka** [comment]
@keichan34 ご連絡と修正ありがとうございます！

**Comment by champierre** [comment]
@jumpei-nishioka 

- 神奈川県厚木市三田2丁目3-6
- 埼玉県深谷市岡1丁目11-10

に関してもデータを追加いたしましたのでお知らせいたします。

**Comment by jumpei-nishioka** [comment]
@champierre 
ありがとうございます！！
