### ISSUE TITLE
チェックリスト

### ISSUE THREAD

**Issue by miya0001** [geolonia/normalize-japanese-addresses#13]
- [x] #12 をマージ
- [x] [このファイル内のテスト](https://github.com/geolonia/community-geocoder/blob/master/test/find.spec.js)を `src/main.test.ts` に移植
- [x] 不動産ID ~~及びcommunity geocoder~~ に組み込み

@kamataryo @naogify 以上お願いします。

**Comment by miya0001** [comment]
あっ、もし都道府県名が抜けている住所に対するテストがあれば、それはとりあえずスルーしてください。

**Comment by naogify** [comment]
@miya0001 

> このファイル内のテストを src/main.test.ts に移植

↓このファイルに移植されていたのですが、これはこのままで良いですか？？
https://github.com/geolonia/normalize-japanese-addresses/blob/master/src/lib/find.test.ts

**Comment by naogify** [comment]
@miya0001 @kamataryo 

> 不動産ID 及びcommunity geocoder に組み込み

のために下の2点のPR送りました! レビューお願いします!

https://github.com/geolonia/normalize-japanese-addresses/pull/39
https://github.com/geolonia/normalize-japanese-addresses/pull/41
