### ISSUE TITLE
愛知県名古屋市北区志賀南通2 のテストケースの追加

### ISSUE THREAD

**Issue by kamataryo** [geolonia/normalize-japanese-addresses#170]
`愛知県名古屋市北区志賀南通二丁目` (正規化可能なケース):
```json
{
  "pref": "愛知県",
  "city": "名古屋市北区",
  "town": "志賀南通二丁目",
  "addr": "",
  "lat": 35.196988,
  "lng": 136.914236,
  "level": 3
}
```

`愛知県名古屋市北区志賀南通2` (正規化できないケース):
```json
{
  "pref": "愛知県",
  "city": "名古屋市北区",
  "town": "",
  "addr": "志賀南通2",
  "lat": null,
  "lng": null,
  "level": 2
}
```

**Comment by RikitoNoto** [comment]
@kamataryo 
こちら修正済みでしょうか？
試したところ両方とも以下の出力でした。
```json
{
  pref: '愛知県',
  city: '名古屋市北区',
  town: '志賀南通二丁目',
  addr: '',
  lat: 35.196988,
  lng: 136.914236,
  level: 3
}
```

**Comment by kamataryo** [comment]
@RikitoNoto 返信遅くなり申し訳ありません。確認いただきありがとうございます！
確かに、直っているようです。
bisect して確認したところ、  7835390bce のコミットに対応が含まれていました！

**Comment by kamataryo** [comment]
こちらの件、解決済みではありますが、 `愛知県名古屋市北区志賀南通2` をテストとして追加したいと思います。
@RikitoNoto もしお時間とご興味があればで大丈夫なのですが、試していただいた結果を assert するテストを追加していただくことできますでしょうか？

**Comment by RikitoNoto** [comment]
@kamataryo 
かしこまりました！
テスト追加してプルリク提出します！

**Comment by kamataryo** [comment]
@RikitoNoto ありがとうございます！確認させていただきます！

**Comment by kamataryo** [comment]
@RikitoNoto プルリクエストをマージしました。ありがとうございました！

**Comment by kamataryo** [comment]
solved by #223
