### ISSUE TITLE
番地部分に不正な数値表現が含まれている時に、クラッシュする

### ISSUE THREAD

**Issue by shio-phys** [geolonia/normalize-japanese-addresses#173]
normalize関数が例外を吐き出すケースがあったのでこちらに起票いたします。
ご対応いただけますと幸いです。

実行環境

```
macOS Monterey 12.3.1(intel)
node v16.15.0
normalize-japanese-addresses v2.5.6
```

NGな例

```
# 「百二三」という数字に変換できない文字列
東京都千代田区永田町百二三
```

OKな例

```
東京都千代田区永田町百二十三
東京都千代田区永田町百二
```

発生する例外:

```
TypeError: The attribute of kanji2number() must be a Japanese numeral as integer.
```

**Comment by kamataryo** [comment]
@shio-phys ありがとうございます。百二三 -> 123 に寄せられると正規化がカバーできる範囲が広がり良さそうです。改善を試みたいと思います。

**Comment by kamataryo** [comment]
@shio-phys こちら、 v2.5.7 で対応いたしました。ぜひお試しください。フィードバックありがとうございました！

**Comment by shio-phys** [comment]
@kamataryo ご対応ありがとうございます！早速新しいバージョンを試してみようと思います！！
