### ISSUE TITLE
〇〇町xxxや、〇〇町小字xxxで終わる住所の場合、市区町村にあたる部分にスペースが入っていると正常に正規化できない

### ISSUE THREAD

**Issue by airhead04** [geolonia/normalize-japanese-addresses#180]
例は多くないですが

NG：スペースあり
京都府京都市　下京区上之町999
{
  "pref": "京都府",
  "city": "",
  "town": "",
  "addr": "京都市 下京区上之町999",
  "lat": null,
  "lng": null,
  "level": 1
}

OK：スペースなし
京都府京都市下京区上之町999
{
  "pref": "京都府",
  "city": "京都市下京区",
  "town": "上之町",
  "addr": "999",
  "lat": 34.988246,
  "lng": 135.749288,
  "level": 3
}

OK：スペースはあるが、〇〇町xxxのパターンで終わっていない
京都府京都市　下京区上之町999-1
{
  "pref": "京都府",
  "city": "京都市下京区",
  "town": "上之町",
  "addr": "999-1",
  "lat": 34.988246,
  "lng": 135.749288,
  "level": 3
}

他には、宮城県仙台市 若林区土樋999　など。

**Comment by kamataryo** [comment]
@airhead04 こんにちは、返答が遅くなり申し訳ありません。こちら、おっしゃる通り特定の条件で住所文字列中のスペースが取り除かれないケースがありました。修正を行った v2.6.1 をリリースしました。フィードバックいただきありがとうございます。
