### ISSUE TITLE
漢数字の後に「の」を含む住所がアラビア数字に変換される

### ISSUE THREAD

**Issue by kacchan6** [geolonia/normalize-japanese-addresses#184]
住所部分の漢数字の後に「の」が含むケース、例えば**一の坂**が**1-坂**になるようです。

一例ですが、**北海道滝川市一の坂町西**を正規化すると**北海道滝川市1-坂町東**になるようです。

他にも類似した事例として**山口県下関市一の宮住吉**は**山口県下関市1-宮住吉**になりますが、
**山口県下関市一の宮学園**は**山口県下関市一の宮学園町**のままのようです。

**Comment by champierre** [comment]
@kacchan6

「北海道滝川市一の坂町西」を正規化しようとした場合、「一の坂町西一丁目」「一の坂町西二丁目」「一の坂町西三丁目」という住所は存在するのですが、「一の坂町西」という住所は存在しないため、完全な正規化には失敗し（正規化レベル2となる）、これまでは正規化に失敗した「一の坂町西」に対して漢数字をアラビア数字に変換するという処理がかかっていました。

v2.7.2 より、正規化できなかった部分には変換処理をおこなわないようにしました。これにより、

北海道滝川市一の坂町西
山口県下関市一の宮住吉

を正規化してもそのままとなりますので、ご確認ください。
