### ISSUE TITLE
表記ゆれ 愛知県津島市池麩町、愛知県安城市柿碕町

### ISSUE THREAD

**Issue by yagumaha** [geolonia/normalize-japanese-addresses#190]
お世話になっております。

以下の住所の場合正規化レベル: [2]になります。
- 愛知県津島市池麩町
- 愛知県安城市柿碕町

それぞれ池麩町=>池麸町, 柿碕町=>柿さき町で正規化レベル: [3] となるのですが、
こちらのゆらぎ対応いただけるでしょうか。

**Comment by kamataryo** [comment]
@yagumaha お返事遅れてしまい申し訳ありませんでした。フィードバックいただきありがとうございます！

池麩町の正規化につきまして、#198 で 麩と麸の揺れを吸収することで対応しました。次のバージョンのリリースの際に取り込ませていただきます。

「柿碕町」と「柿さき町」の正規化について、かなと漢字の揺れを吸収する機能はなく、現在のところ実現するのは少し難しいように感じています。実現できれば大変便利だと思いますので、この issue はオープンのままにさせていただき方法を考えていきたいと思います。
もし良いアイデアやデータソースなどの情報ありましたらお寄せいただければ幸いです。

**Comment by kamataryo** [comment]
@yagumaha  「柿碕町」と「柿さき町」の正規化に #202 で対応しました。こちら、ふりがなの情報を処理するのではなく、「柿碕町」を決めうちで文字列処理で正規化するように対応しました。
次のバージョンのリリースの際に取り込ませていただきます。

**Comment by yagumaha** [comment]
@kamataryo 
対応いただきありがとうございます!

**Comment by kamataryo** [comment]
@yagumaha こちらの機能、バージョン 2.8.0 としてリリースしました！
ぜひまたお試しください。取り急ぎお知らせまで。

**Comment by yagumaha** [comment]
対応してくださり、ありがとうございました！
