### ISSUE TITLE
自動リリースの GitHub Actions の修正

### ISSUE THREAD

**Issue by kamataryo** [geolonia/normalize-japanese-addresses#222]
ブランチでも自動リリース作成ワークフローが動作しているようでした。
`v*.*.*` のタグだけの場合に限定したいと考えています。
https://github.com/geolonia/normalize-japanese-addresses/actions/runs/6037039730/job/16380522940

**Comment by RikitoNoto** [comment]
こんばんは！
すみません、私の設定にミスがあったみたいです。
github actionsのドキュメントを見直したのですが、そもそもcreateはtagのみを限定などはできなさそうでした。
<img width="1141" alt="image" src="https://github.com/geolonia/normalize-japanese-addresses/assets/56541594/0a1d0f2a-1cba-41a1-b631-4d0cd30791aa">

使えそうな物を探したのですが、以下のon push構文が使えそうでしたがいかがでしょうか？
<img width="709" alt="image" src="https://github.com/geolonia/normalize-japanese-addresses/assets/56541594/67824b48-8e1e-4a72-9c62-0f10fe904baf">

**Comment by kamataryo** [comment]
@RikitoNoto ありがとうございます！
なるほど、create と push の違いをあまり意識できていませんでした。
今のワークフローは、メンテナーがリリースのタイミングで main ブランチからタグを作成してプッシュすることでリリースとしていますので、 `on.push` で問題ないかと思います..🤔

もしよろしければ、修正をプルリクエストとしていただくこと可能でしょうか？

**Comment by RikitoNoto** [comment]
@kamataryo 
ご返信ありがとうございます！
かしこまりました！プルリクエスト後日作成いたします！

**Comment by kamataryo** [comment]
@RikitoNoto v2.10.0 としてリリースしました！正しく動作しているようです。ありがとうございました！

Actions: https://github.com/geolonia/normalize-japanese-addresses/actions/runs/6647841669/job/18063937226
リリースページ: https://github.com/geolonia/normalize-japanese-addresses/releases/tag/v2.10.0
