### ISSUE TITLE
有关脑控装置

### ISSUE THREAD

**Issue by Yemaozibuchiyu** [geolonia/normalize-japanese-addresses#224]
大陆这边玩上脑控装置了，玩的可嗨了，有没有感兴趣的过来参与，地址是辽宁省本溪市明山区春明街附近。感兴趣的可以过来玩玩，欢迎光临。

技术体现： 
                  脑内成像技术，脑电信号映射到目标人脑，通过软体调整参数控制电信号，将需要传输的信息通过该信号传输至人脑。传输至 
                  人脑后的信息可构成画面以及音声。

**Comment by Yemaozibuchiyu** [comment]
非连线装置，可远程信号传输控制。感兴趣的可以过来看看。

**Comment by kamataryo** [comment]
@Yemaozibuchiyu Hi, your topic seems not to related current project. We are closing this issue.
