### ISSUE TITLE
テスト項目の重複と、テスト用住所の船と舟のゆらぎ

### ISSUE THREAD

**Issue by mikihiro-t** [geolonia/normalize-japanese-addresses#229]
C#への移植をある程度できたところで（修正点が残っています）、ユニットテストがほぼ成功した段階です。
テスト部分を移植したところ、テスト項目の重複が多数あるのと、テスト用住所の誤りが１件ありました。

### テストが重複

`和歌山県東牟婁郡串本町串本千二百三十四`

`大阪府大阪市此花区西九条3-2-16`

`岡山県笠岡市大宜1249－1`
（「岡山県笠岡市大冝1249－1」ではない方　→「大冝」ではない方）

### テスト住所の誤り？
```
    test('京都府京都市中京区河原町二条下ル一之舟入町537-50（船と舟のゆらぎ）', async () => {
      const res = await normalize('京都府京都市中京区河原町二条下ル一之船入町537-50')
```

は、const resの２行目の「船入町」は「舟入町」だと思います。

## list.txtとaddresses.csv
以下、重複しています。

東京都新宿区市谷加賀町２丁目６－１
東京都渋谷区神泉町１７－１４
東京都目黒区大橋１丁目１０－１
東京都豊島区池袋本町１丁目１５－１０
東京都台東区上野２丁目１１－２０
東京都世田谷区中町２丁目９－２５
東京都世田谷区北烏山３丁目１０－１２
東京都新宿区北新宿１丁目２０－１０
東京都渋谷区神南１丁目８－１８
東京都渋谷区南平台町５－１２
東京都江東区大島２丁目３３－１０
神奈川県川崎市麻生区上麻生３丁目１５－７
神奈川県横浜市都筑区中川６丁目１
神奈川県横浜市青葉区新石川３丁目３－１５
神奈川県横浜市都筑区中川１丁目２９
東京都目黒区中根２丁目６－１９
東京都目黒区下目黒６丁目１９－１
東京都目黒区目黒本町２丁目７－５
東京都目黒区緑が丘２丁目２３－１６
東京都練馬区関町北４丁目２１－６７
東京都目黒区大橋１丁目５－１
東京都立川市若葉町１丁目２４－３０
東京都文京区湯島１丁目２－１０
東京都文京区向丘２丁目２８－１３
東京都墨田区京島１丁目１－１
東京都東久留米市八幡町１丁目９－２８
東京都品川区大崎２丁目９－２
東京都品川区勝島１丁目４－２０
東京都中野区鷺宮６丁目２８－２３
東京都調布市下石原２丁目５－１５
東京都中野区大和町３丁目３５－１０
東京都品川区戸越６丁目２－１６
東京都中野区中央５丁目６－２１
東京都品川区大崎２丁目９－１
東京都町田市鶴間２丁目６－１７
東京都品川区東五反田１丁目２－４５
東京都調布市下石原１丁目１８－４
東京都品川区東五反田２丁目４－４
東京都大田区萩中３丁目１７－７
東京都中央区勝どき５丁目３－１
東京都中央区銀座７丁目１８－１３
東京都中央区月島３丁目３２－１
東京都大田区南雪谷２丁目１１－１６
東京都中央区晴海２丁目３－２
東京都大田区南雪谷３丁目１７－３
東京都中央区日本橋人形町１丁目１２－１１
東京都世田谷区桜上水１丁目１４－９
東京都世田谷区池尻４丁目８－１
東京都世田谷区太子堂４丁目３０－３１
東京都世田谷区上用賀５丁目９－１
東京都世田谷区中町２丁目９－２４
東京都世田谷区中町４丁目３２－３
東京都世田谷区上北沢１丁目１５－３０
東京都世田谷区中町４丁目５－１５
東京都千代田区外神田２丁目１７－６
東京都世田谷区梅丘２丁目１０－１６
東京都世田谷区奥沢１丁目２７－７
東京都小平市学園東町２丁目１６－１９－４
東京都新宿区歌舞伎町２丁目９－１５
東京都新宿区払方町４－３
東京都新宿区余丁町６－２８
東京都世田谷区弦巻１丁目４５－１３
東京都杉並区荻窪４丁目３３－９
東京都新宿区市谷薬王寺町７４
東京都世田谷区奥沢７丁目２３－１８
東京都新宿区南榎町５４
東京都新宿区余丁町８－１０
東京都荒川区南千住８丁目１１－１
東京都渋谷区広尾５丁目８－１９
東京都渋谷区恵比寿西２丁目２０－７
東京都港区新橋４丁目９－１
東京都港区芝浦４丁目１０－１
東京都港区南青山４丁目２７－２３
東京都荒川区南千住８丁目３－２
東京都港区南麻布２丁目２－４
東京都渋谷区広尾３丁目１７－２７
東京都港区南麻布５丁目１０－２７
東京都渋谷区渋谷１丁目１－６
東京都港区白金台３丁目１２－４
東京都渋谷区代々木２丁目２６－５
東京都港区麻布狸穴町４４－１
東京都渋谷区南平台町６－１１
東京都港区三田５丁目１２－３
東京都江東区南砂３丁目８－２
大阪府大阪市中央区本町橋１－５
東京都港区芝４丁目１６－１
大阪府大阪市平野区瓜破東３丁目１－６
東京都江東区大島６丁目１５－２
大阪府大阪市北区神山町１－３３
東京都港区港南２丁目１２－２８
大阪府大阪市淀川区十八条１丁目１－３２
東京都港区三田５丁目１３－８
大阪府箕面市新稲３丁目３－１０
東京都港区芝２丁目１－２５
千葉県船橋市湊町２丁目８－４０
千葉県千葉市美浜区高浜３丁目５
大阪府摂津市千里丘新町５－２２
神奈川県藤沢市大庭５５２６－２０
大阪府大阪市中央区南船場１丁目１２－２２
神奈川県藤沢市藤沢５７５－１
千葉県流山市加１丁目１２－１
千葉県市川市市川２丁目３２－２１
千葉県習志野市大久保２丁目１８－１０
大阪府大阪市中央区谷町２丁目２番１３
神奈川県川崎市中原区小杉町３丁目１３０１
神奈川県川崎市中原区中丸子１２４６－１
神奈川県鎌倉市植木８４１－１
神奈川県川崎市宮前区馬絹６丁目２０－１５
神奈川県川崎市宮前区宮前平２丁目５－８
神奈川県川崎市中原区新丸子東３丁目１３０１
神奈川県川崎市宮前区鷺沼４丁目１４－２
神奈川県川崎市中原区中丸子１３－７
神奈川県川崎市宮前区小台２丁目１２－９
神奈川県川崎市麻生区片平１丁目９－５
神奈川県川崎市宮前区土橋１丁目８－２
神奈川県川崎市高津区下作延６丁目３０－１
神奈川県横浜市保土ケ谷区川辺町２－２
神奈川県横浜市青葉区新石川４丁目１７－２
神奈川県横浜市西区みなとみらい６丁目３－４
神奈川県横浜市青葉区藤が丘１丁目１６－３２
神奈川県横浜市青葉区荏田西１丁目１０－４
神奈川県横浜市瀬谷区二ツ橋町２２３－１
神奈川県横浜市青葉区荏田西２丁目３７－１１
神奈川県横浜市南区中村町４丁目２７４－３
神奈川県横浜市青葉区荏田町３５３－１
神奈川県横浜市青葉区荏田北３丁目１６－９
神奈川県横浜市緑区長津田６丁目１－６
神奈川県横浜市港南区丸山台１丁目１６－２７
埼玉県所沢市元町２８－９
埼玉県さいたま市南区別所７丁目２－１
京都府京都市左京区秋築町２３７－１
神奈川県横浜市磯子区森４丁目３－４
埼玉県さいたま市浦和区常盤１丁目６－２１
神奈川県横浜市港北区新羽町７９０
埼玉県さいたま市浦和区針ヶ谷１丁目５－１
愛知県春日井市高蔵寺町２丁目２７

**Comment by kamataryo** [comment]
@mikihiro-t ありがとうございます！
 こちら #232 でテストのリファクタリング（+1件不正なテスト（舟入町のケース）の修正）として対応しました 🙇
