### ISSUE TITLE
.NET版 作成

### ISSUE THREAD

**Issue by mikihiro-t** [geolonia/normalize-japanese-addresses#230]
便利なライブラリありがとうございます。

.NET版を作成しました。
[NormalizeJapaneseAddressesNET](https://github.com/mikihiro-t/NormalizeJapaneseAddressesNET)

技術的な解説は、Qiitaに載せる予定です。

今後も、ライブラリの変更を反映していきたいと思います。
よろしくお願いします。

**Comment by kamataryo** [comment]
@mikihiro-t 素晴らしいです！近いうちにコンパイルして試してみたいと思います。
お知らせいただきありがとうございます！
