### ISSUE TITLE
「崎」「﨑」の表記揺れ

### ISSUE THREAD

**Issue by mikihiro-t** [geolonia/normalize-japanese-addresses#233]
「崎」「﨑」は、どちらも同じ字なので、本来どちらを利用しても良いらしいです。
https://sumisalon.com/saki/
https://ja.wiktionary.org/wiki/%E5%B4%8E

latest.csvの住所データでよく利用されているのは「崎」ですが、
「﨑」も1つあります。「奈良県宇陀市菟田野岩﨑」
https://www.city.uda.nara.jp/soumu/kurashi/sumai/juusho/utano.html

■表記揺れの例
ひたちなか市磯「崎」町が通常使われていますが、

下記の学校コードの住所では、
茨城県ひたちなか市磯「﨑」町５１３５
https://www.mext.go.jp/b_menu/toukei/mext_01087.html
が使われました。

以上をふまえて、
dict.tsの、toRegexPattern で処理すると良いように思えますが、どうでしょうか。

**Comment by keichan34** [comment]
@mikihiro-t こちらの対応が遅れて大変申し訳ありません！
v3リリースと共に追加しておきました。こちらで確認できます:

* [﨑→崎](https://geolonia.github.io/normalize-japanese-addresses/#q=%E8%8C%A8%E5%9F%8E%E7%9C%8C%E3%81%B2%E3%81%9F%E3%81%A1%E3%81%AA%E3%81%8B%E5%B8%82%E7%A3%AF%EF%A8%91%E7%94%BA%EF%BC%95%EF%BC%91%EF%BC%93%EF%BC%95)
* [崎→﨑](https://geolonia.github.io/normalize-japanese-addresses/#q=%E5%A5%88%E8%89%AF%E7%9C%8C%E5%AE%87%E9%99%80%E5%B8%82%E8%8F%9F%E7%94%B0%E9%87%8E%E5%B2%A9%E5%B4%8E)

報告ありがとうございました！
