### ISSUE TITLE
v3　type error

### ISSUE THREAD

**Issue by keesmark** [geolonia/normalize-japanese-addresses#242]
v3にバージョンアップすると以下のエラーが出ます。
```
Cannot find module '@geolonia/normalize-japanese-addresses' or its corresponding type declarations.
```

**Comment by keichan34** [comment]
3.0.1 リリースしました。ご確認いただければと思います。
https://www.npmjs.com/package/@geolonia/normalize-japanese-addresses
まだ発生する場合は、利用環境を教えていただけると助かります、、 :bow:

**Comment by keichan34** [comment]
こちらの方では確認を取っているので一旦issueをクローズさせていただきます。もし環境によってまだ発生しているようであれば、その環境を再現できるために詳細を教えていただき reopen してくださいー。

報告ありがとうございました！
