### ISSUE TITLE
v3 type error (前回に引き続き)

### ISSUE THREAD

**Issue by keesmark** [geolonia/normalize-japanese-addresses#245]
https://github.com/geolonia/normalize-japanese-addresses/issues/242

前回の対応ありがとうございました！
ですが、僕の環境ので再度行ったところまだエラーになるようなので、再度issueを立てました！
Next.jsで使っていて前のV2の時にはなかったエラーになってます。
試すために、Page routerとApp routerどちらも試していますが、同じ結果となりました。
よろしくおねがします！

別途情報が必要な場合はお知らせください！

error
```
Cannot find module '@geolonia/normalize-japanese-addresses' or its corresponding type declarations.
```

import
```typescript
import { normalize } from "@geolonia/normalize-japanese-addresses";
```

実行環境
```
next.js: v14.2.7
@geolonia/normalize-japanese-addresses: ^3.0.1
node.js: v20.18.0
typescript: ^5
pnpm: 9.12.2
```

**Comment by keichan34** [comment]
@keesmark 報告ありがとうございました。以前の修正で直らなかったんですね、、こちらの環境で再現し、また連絡させていただきます。

**Comment by keichan34** [comment]
こちら確認でき、修正を用意しましたので一旦このissueをクローズします。他の機能も含めて今日中にリリースする予定なので、またリリースしたら連絡します :bow:
今度はwebpack周りの相性でした、、今後の安定性を維持するためにwebpackなどの結合テストも導入することにしました

**Comment by keichan34** [comment]
@keesmark リリースしました: https://github.com/geolonia/normalize-japanese-addresses/releases/tag/v3.1.0
ご確認のほど、よろしくお願い致します。
