### ISSUE TITLE
config.japaneseAddressesApiオプションでローカルのjapanese-addresses-v2を参照できない

### ISSUE THREAD

**Issue by kurashina-design** [geolonia/normalize-japanese-addresses#250]
japanese-addresses-v2をビルドしたものをローカルにおいて、`config.japaneseAddressesApi`で読み込みながら正規化をかけた場合、下記のエラーが出て実行できません。

ソースコード上の参照指定
`config.japaneseAddressesApi` = `file://${path.resolve('japanese-addresses-v2')}/api/ja;`

エラー内容：
`TypeError [ERR_INVALID_ARG_VALUE]: The argument 'flags' is invalid. Received 'rb'`

Node.jsのfsモジュールのopenメソッドのフラグにrbが設定されていますが、それが原因とエラーを読むと思いましたのでrbをrにするとこちらの環境では実行可能となりました。

OS: macOS
Node: v22.10.0
normalize-japanese-address: v3.1.0 
japanese-addresses-v2:  v0.0.5

**Comment by kaneda-1954** [comment]
ご修正ありがとうございました。
