### ISSUE TITLE
tree.json のバンドルを辞めて新しい形でデータを取得できるようにする

### ISSUE THREAD

**Issue by kamataryo** [geolonia/normalize-japanese-addresses#7]

**Comment by kamataryo** [comment]
以下でコメントしたように、現状では位置参照情報の最新のデータを扱えないことに留意する。
https://github.com/geolonia/normalize-japanese-addresses/pull/8#issue-497392655

tree.json に変わる方法を開発する際には新しくなっているデータ形式に合わせて設計する。

**Comment by miya0001** [comment]
API 化したので閉じる
